# Generated by Django 3.2.13 on 2023-08-04 16:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_path', jsonfield.fields.JSONField(blank=True, null=True)),
                ('alternative_paths', jsonfield.fields.JSONField(blank=True, null=True)),
                ('termination_points', models.ManyToManyField(related_name='termination_points', to='nodes.TerminationPoint')),
            ],
        ),
    ]
